/**
 * genKatexAssets.mjs
 * ──────────────────
 * Bundles KaTeX for TRUE offline rendering inside the MathText WebView.
 *
 * React Native can't read files from disk at runtime, so we snapshot the
 * installed `katex` package into a plain TS module (`src/components/katexAssets.ts`)
 * that Metro bundles:
 *   - KATEX_CSS : katex.min.css with every woff2 font inlined as a base64
 *                 data: URI (the woff/ttf fallbacks are dropped so the WebView
 *                 never attempts a network request), and
 *   - KATEX_JS  : katex.min.js + contrib/auto-render.min.js concatenated.
 *
 * Re-run after upgrading katex:  node scripts/genKatexAssets.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'node_modules', 'katex', 'dist');
const fontsDir = join(dist, 'fonts');
const outFile = join(here, '..', 'src', 'components', 'katexAssets.ts');

// 1. Inline every woff2 font as a base64 data URI, keyed by filename.
const fontData = {};
for (const f of readdirSync(fontsDir)) {
  if (f.endsWith('.woff2')) {
    fontData[f] = readFileSync(join(fontsDir, f)).toString('base64');
  }
}

// 2. Rewrite the CSS @font-face src lists to point at the inlined woff2 only.
let css = readFileSync(join(dist, 'katex.min.css'), 'utf8');
css = css.replace(
  /src:url\(fonts\/([\w-]+)\.woff2\)[^;}]*/g,
  (whole, name) => {
    const b64 = fontData[`${name}.woff2`];
    if (!b64) return whole; // unknown font — leave untouched
    return `src:url(data:font/woff2;base64,${b64}) format("woff2")`;
  },
);

// 3. Concatenate the KaTeX engine + auto-render helper. Escape any </script>
//    so the blob can't terminate the host <script> tag when embedded.
const js =
  readFileSync(join(dist, 'katex.min.js'), 'utf8') +
  '\n' +
  readFileSync(join(dist, 'contrib', 'auto-render.min.js'), 'utf8');
const jsSafe = js.replace(/<\/script>/gi, '<\\/script>');

const banner =
  '// AUTO-GENERATED by scripts/genKatexAssets.mjs — do not edit by hand.\n' +
  '// KaTeX CSS (woff2 fonts inlined as base64) + JS, snapshotted for offline\n' +
  '// rendering in the MathText WebView. Regenerate after upgrading katex.\n' +
  '/* eslint-disable */\n';

const body =
  banner +
  `export const KATEX_CSS: string = ${JSON.stringify(css)};\n` +
  `export const KATEX_JS: string = ${JSON.stringify(jsSafe)};\n`;

writeFileSync(outFile, body);

const kb = (n) => (n / 1024).toFixed(0);
console.log(
  `Wrote ${outFile}\n  fonts inlined: ${Object.keys(fontData).length}` +
    `\n  CSS: ${kb(css.length)} KB  JS: ${kb(jsSafe.length)} KB` +
    `\n  total module: ${kb(body.length)} KB`,
);
